---
title: "Resources for Using R"
author: "David J. Hunter"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    df_print: paged
    theme: spacelab
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This site was originally created for a faculty workshop held at Westmont College in May of 2019. The purpose of the workshop is to introduce colleagues from a range of disciplines to R, giving them resources for using R in their teaching and research.

# Workshop Slides 

## [Getting started: Variables, Data Frames, and Workflow](slides/getting_started.html) 

This lesson starts with the basics of executing commands in the console and introduces the fundamental ways that R stores data. We will also see how to use R scripts and RMarkdown documents to encourage habits of *reproducibility* in your teaching and research. 

## [Introductory Statistics in 5 Minutes](slides/intro_stats.html) 

Once you are comfortable with data frames in R and the RStudio interface, most basic statistical tests can be run in a single line of code. We will see how to perform one- and two-sample $t$-tests, paired $t$-tests, $\chi^2$-tests, one-way and factorial ANOVA (including post-hoc tests), correlation and regression, multiple regression, and more. 

## [Dealing with Data and Packages](slides/data_pack.html) 

Unleash the power of using *packages* to extend R's capabilities. We will focus on using the [tidyverse](https://www.tidyverse.org/) to import data and shape it in a reproducible way.

## [Graphics](slides/graphics.html) 

Get started using the [ggplot2](https://ggplot2.tidyverse.org/) library to create publication-ready graphics quickly and easily.

## [Functions, Vectorization, Replication](slides/functions.html)

Streamline your projects by writing your own functions, and apply them over a range of data using *vectorization* instead of iteration.

# Other resources

## [Worksheets](worksheets/index.html)

This page contains an index of the RMarkdown worksheets that go with the slides.

## Data files

- [crickets.csv](data/crickets.csv)

## Workshop Prerequisites

* Bring a laptop that uses OSX, Windows, or Linux. (If you would like to use a Chromebook, let me know and I will give you an account on our statistics server.)
* Install R and RStudio on your laptop.
    + **First,** [download and install R](https://cran.rstudio.com/).
    + **Second,** [download and install RStudio](https://www.rstudio.com/products/rstudio/download/).
    
# Helpful websites

* The [CRAN Task Views page](https://cran.rstudio.com/web/views/) is a good place to discover hundreds (thousands?) of popular R packages, organized by discipline, available from the [Comprehensive R Archive Network](https://cran.rstudio.com/).
* [The R Inferno](https://www.burns-stat.com/pages/Tutor/R_inferno.pdf), by Patrick Burns, is a helpful guide for programmers who want to understand how R is different from other programming languages.
* [Most upvoted Stack Overflow R questions](https://stackoverflow.com/questions/tagged/r)
* [Choosing the right statistical test](https://stats.idre.ucla.edu/other/mult-pkg/whatstat/), with code samples in R, SPSS, SAS, and Stata. 
* [R For Data Science](https://r4ds.had.co.nz/), by Hadley Wickham and Garrett Grolemund.

# Source Code

All of the pages and slides on this site were authored in RMarkdown. The source code is available on GitHub: https://github.com/djhunter/Rworkshop

